apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating
webhooks:
- name: mutating.kube-ops.svc
  clientConfig:
    caBundle: <ca_
    service:
      name: mutating
      namespace: kube-ops
      path: "/mutating"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
  # namespaceSelector:
  objectSelector:
    matchLabels:
      pod-injection: enabled
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
